# Generated by Django 4.0.4 on 2022-05-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('salary_month', models.CharField(max_length=8)),
                ('workers_needed', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=3)),
                ('year_start', models.CharField(max_length=4)),
                ('month_start', models.CharField(max_length=2)),
                ('day_start', models.CharField(max_length=2)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study_app.job')),
            ],
        ),
    ]
