# Generated by Django 4.0.4 on 2022-05-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=30, verbose_name='El Nombre'),
        ),
    ]
